version: "3.8"

services:
    sqlserver:
        container_name: sqlserver
        image: mcr.microsoft.com/mssql/server
        ports:
            - "1443:1443"
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=myStrongPassword12#
        volumes:
            - sqldata:/var/opt/sqldata
        deploy:
            resources:
                reservations:
                    cpus: '2'
                    memory: 2GB
                
    web_app:
        container_name: webapp
        image: indominuscontactscr.azurecr.io/library/web-app
        ports:
            - "80:80"
        restart: on-failure
        domainname: indominus-exam

volumes:
    sqldata:
        driver: azure_file
        driver_opts:
            share_name: sql-volume
            storage_account_name: indominuscontactsa